version: '3.8'

services:
  payment-notification:
    build: .
    container_name: payment-notification-handler
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # These should be set in your .env file or passed via docker-compose.override.yml
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - MIDTRANS_SERVER_KEY=${MIDTRANS_SERVER_KEY}
    restart: unless-stopped
    # Increase memory and CPU limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    # Fix health check timing
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health", "||", "exit", "1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - payment-network

networks:
  payment-network:
    driver: bridge 